name: Flutter Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, release, develop, main_front, back, 'feature/**' ]

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Flutter action
        uses: subosito/flutter-action@v2.3.0

      - name: Prepare for Firebase
        env:
          OPTIONS: ${{ secrets.FIREBASE_OPTIONS }}
        run: |
          echo $OPTIONS > lib/firebase_options.dart

      - name: Install dependencies
        run: flutter pub get

      - name: Test flutter app
        run: flutter test