name: Flutter Test & Deploy

on:
  push:
    tags:
      - 'v*'

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Flutter action
        uses: subosito/flutter-action@v2.3.0

      - name: Prepare for Firebase
        env:
          OPTIONS: ${{ secrets.FIREBASE_OPTIONS_TAG }}
          GOOGLE_KEY: ${{ secrets.GOOGLE_SERVICES }}
        run: |
          echo $OPTIONS | base64 --decode > lib/firebase_options.dart
          echo $GOOGLE_KEY | base64 --decode > android/app/google-services.json

      - name: Install dependencies
        run: flutter pub get

      - name: Test flutter app
        run: flutter test

  BuildAPK:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    needs: [ Test ]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Flutter action
        uses: subosito/flutter-action@v2.8.0

      - name: Prepare for Firebase
        env:
          OPTIONS: ${{ secrets.FIREBASE_OPTIONS_TAG }}
          GOOGLE_KEY: ${{ secrets.GOOGLE_SERVICES }}
        run: |
          echo $OPTIONS | base64 --decode > lib/firebase_options.dart
          echo $GOOGLE_KEY | base64 --decode > android/app/google-services.json

      - name: Install dependencies
        run: flutter pub get

      - name: Build android app(.apk)
        run: flutter build apk

      - name: Rename .apk file
        run: mv build/app/outputs/flutter-apk/app-release.apk tag_management.apk

      - name: Upload apk file
        uses: actions/upload-artifact@v3
        with:
          name: output
          path: tag_management.apk
          if-no-files-found: error

  Deploy:
    runs-on: ubuntu-latest
    needs: [ BuildAPK ]
    steps:
      - name: Download files
        uses: actions/download-artifact@v3
        with:
          name: output

      - name: Display structure of downloaded files
        run: ls -R

      - name: Upload to github release
        uses: fnkr/github-action-ghr@v1
        env:
          GHR_PATH: tag_management.apk
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
