name: Project Management

on: issue_comment

jobs:
  fixing-issue-founded:
    name: 작업 진행 확인 시 진행중으로 표시
    if: ${{ !github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.3
        with:
          project: 전자출결 개선 프로젝트
          column: 진행중
          repo-token: ${{ secrets.GITHUB_TOKEN }}

  fixed-issue-founded:
    name: 작업 완료 후 PR시 준비됨으로 표시
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.3
        with:
          project: 전자출결 개선 프로젝트
          column: 준비됨
          repo-token: ${{ secrets.GITHUB_TOKEN }}